/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JosefRouteImport } from './routes/josef'
import { Route as BestTeacherEverRouteImport } from './routes/best-teacher-ever'
import { Route as IndexRouteImport } from './routes/index'

const JosefRoute = JosefRouteImport.update({
  id: '/josef',
  path: '/josef',
  getParentRoute: () => rootRouteImport,
} as any)
const BestTeacherEverRoute = BestTeacherEverRouteImport.update({
  id: '/best-teacher-ever',
  path: '/best-teacher-ever',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-teacher-ever': typeof BestTeacherEverRoute
  '/josef': typeof JosefRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-teacher-ever': typeof BestTeacherEverRoute
  '/josef': typeof JosefRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-teacher-ever': typeof BestTeacherEverRoute
  '/josef': typeof JosefRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/best-teacher-ever' | '/josef'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/best-teacher-ever' | '/josef'
  id: '__root__' | '/' | '/best-teacher-ever' | '/josef'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestTeacherEverRoute: typeof BestTeacherEverRoute
  JosefRoute: typeof JosefRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/josef': {
      id: '/josef'
      path: '/josef'
      fullPath: '/josef'
      preLoaderRoute: typeof JosefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-teacher-ever': {
      id: '/best-teacher-ever'
      path: '/best-teacher-ever'
      fullPath: '/best-teacher-ever'
      preLoaderRoute: typeof BestTeacherEverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestTeacherEverRoute: BestTeacherEverRoute,
  JosefRoute: JosefRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
